name: Terraform module tests

on:
  workflow_dispatch:
    inputs:
      charm-path:
        description: "Charm root in this repository"
        default: '.'
        required: false
        type: string
      provider:
        description: |
          The substrate to set up prior to running the test 
          (a concierge preset, e.g. 'lxd' or 'k8s').
        default: 'k8s'
        required: false
        type: string

jobs:
    tf-tests:
        runs-on: [self-hosted]
        name: Terraform tests
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install dependencies
            run: |
              sudo snap install concierge --classic
              sudo concierge prepare -p {{ inputs.provider }} --extra-snaps terraform,astral-uv
          - name: Run tests
              cd "${{ inputs.charm-path }}"
              tox -e terraform
              
          
