name: Terraform module tests

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Charm root in this repository"
        default: '.'
        required: false
        type: string
      charm-channel:
        description: "Charm channel to deploy from with the terraform module"
        default: '2/edge'
        required: false
        type: string
      provider:
        description: |
          The substrate to set up prior to running the test 
          (a concierge preset, e.g. 'machine' or 'microk8s').
        default: 'microk8s'
        required: false
        type: string

jobs:
    tf-tests:
        runs-on: [self-hosted, amd64]
        name: Terraform tests
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install dependencies
            run: |
              sudo snap install concierge --classic
              sudo concierge prepare -p ${{ inputs.provider }} --extra-snaps terraform,astral-uv
          - name: Run tests
            run: |
              cd "${{ inputs.charm-path }}"
              export CHARM_CHANNEL=${{ inputs.charm-channel }}
              uvx tox -e terraform
              
          
