name: Terraform module tests

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 7,14,21 * *"
#              │ │    │    │ │
#              │ │    │    │ └──── any day of the week.
#              │ │    │    └────── any month.
#              │ │    └─────────── 7th, 14th, 21st day of the month.
#              │ └──────────────── 0th hour of the day.
#              └────────────────── Start of the hour (minutes = 0).

jobs:
  - uses: ./_terraform-tests.yaml
    with:
      provider: lxd
