name: Terraform module tests

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 7,14,21 * *"
#              │ │    │    │ │
#              │ │    │    │ └──── any day of the week.
#              │ │    │    └────── any month.
#              │ │    └─────────── 7th, 14th, 21st day of the month.
#              │ └──────────────── 0th hour of the day.
#              └────────────────── Start of the hour (minutes = 0).

jobs:
  terraform-tests:
    name: Run terraform tests
    uses: ./.github/workflows/_terraform-tests-auto.yaml
    with:
      provider: machine
      charm-channel: 2/edge
    secrets: inherit
